### ISSUE TITLE
Compatibility with master version of Leaflet

### ISSUE THREAD

**Issue by pufanalexandru** [CliffCloud/Leaflet.sleep#1]
Hello and thanks for this useful plugin.

Right now, in the master version of Leaflet, the sleepNote dissapears after a second or less, any plans to make this work properly?

**Comment by atstp** [comment]
I'll check it out this week, thanks for the heads up!

**Comment by dmitry** [comment]
@atstp any update on this?

**Comment by atstp** [comment]
@dmitry it's fixed, thanks for mentioning it again!

@pufanalexandru sorry for the wait!
