### ISSUE TITLE
Leaflet no loading on demo page

### ISSUE THREAD

**Issue by clintharris** [CliffCloud/Leaflet.sleep#13]
https://cliffcloud.github.io/Leaflet.Sleep/

`L is not defined`

**Comment by jpcartailler** [comment]
The page is trying to load mixed (http and https) content. Try http://cliffcloud.github.io/Leaflet.Sleep/.

**Comment by clintharris** [comment]
Thanks!

**Comment by maratumba** [comment]
Demo still not loading leaflet due to mixed content.
