### ISSUE TITLE
Hover activation - only when mouse stops moving?

### ISSUE THREAD

**Issue by si-the-pie** [CliffCloud/Leaflet.sleep#19]
Currently the timer for hover activation starts when the mouse moves over the map.

This means that the map comes alive while the mouse is moving around.

Instead I'd like that timer to start only when the mouse has stopped moving relative to the map. If the mouse stops for sufficient time (the wakeTime) only then should the map activate.

**Comment by atstp** [comment]
When it's time to do a rewrite here, I'll certainly work this in.  

In the meantime, increasing the `wakeTime` will make the map less sensitive to waking.

If you're itching for the exact functionality now though, feel free to sumit a PR!
