### ISSUE TITLE
Kudos/ proposal

### ISSUE THREAD

**Issue by MikeMuxika** [CliffCloud/Leaflet.sleep#20]
Hey, cool project! 

Not sure if they or you would even be up for it but it would be really cool to see this project merged or brought into https://github.com/PaulLeCam/react-leaflet. I think this has the potential to really compliment what is being built there.

**Comment by atstp** [comment]
Thanks for the suggestion, I'll take a look into it!

In the meantime, i'll close this issue because it relates more to the code of react-leaflet than this project.

Also, the code here is under the MIT license, so you're free to take/copy/reuse/alter it if you want to submit a PR to react-leaflet.
