### ISSUE TITLE
Replace sleepButton prompt?

### ISSUE THREAD

**Issue by Spone** [CliffCloud/Leaflet.sleep#24]
Hello,

in order to internationalize my app, I'd like to override the "disable map" string from here: https://github.com/CliffCloud/Leaflet.Sleep/blob/master/Leaflet.Sleep.js#L17

How should I proceed?

Thanks.

**Comment by atstp** [comment]
Here are [the docs](http://leafletjs.com/reference.html#class-options) for leaflet's base class.

As you found, prompt is an `option` on `L.Control.SleepMapControl`, and leaflet's map class (L.Map) is [extended](https://github.com/CliffCloud/Leaflet.Sleep/blob/master/Leaflet.Sleep.js#L69) to take a default factory function for a `sleepButton`.  

For what you're asking, you'd want to

  * make a new factory that produces a new button with your controls
  * merge leaflet's map options to use the factory for your new control

here's an untested sketch of what it sounds like you're trying to do

```
// METHOD 1
// extend L.Control.SleepMapControl to an internationalized version
var InternationalizedSleepControl = L.Control.SleepMapControl.extend({
    // might need an init function
    options: {
        prompt: '<internationalized prompt>',
    }  
})

// make a factory for L.Map's options
var internationalizedSleepControl = function(){
    return new InternationalizedSleepControl();
}

// set the factory as the map's default
L.Map.mergeOptions({
    sleepButton: internationalizedSleepControl
});
```

That's verbose, but it goes over everything that "needs" to happen. If you're looking to cut some corners you should also be able to do something like 

```
// METHOD 2
L.Map.mergeOptions({
    sleepButton: function(){
        return new L.Control.SleepMapControl({ prompt: "<internationalized prompt>" });
    },
});
```

or  without altering any base classes

```
// METHOD 3
var myMap = L.map('my-map', {
    sleepButton: function(){
        return new L.Control.SleepMapControl({ prompt: "<internationalized prompt>" });
    },
});
```

Like i said, that's all untested, so you might get some typos, and I can't say for sure whether it's perfect. Either way, it should be a good jumping off point.  

Let me know if you run into any more trouble

**Comment by Spone** [comment]
Thanks for you very detailed answer. I'll try these methods and let you know how it goes.

**Comment by Spone** [comment]
I used the 3rd method, it's concise and works great.
