### ISSUE TITLE
On Touch Devices: Can't Enable Map after Disable

### ISSUE THREAD

**Issue by tschopo** [CliffCloud/Leaflet.sleep#28]
Once pressing "disable" the Map cannot be reenabled. This happens on touch devices (Tested on Android 6.0.1 with Firefox for Android 58.0.1).

https://jsfiddle.net/9p4Lugsm/

Reenabling doesn't work if you click the disable button and then scroll. However it does work when you do not scroll after clicking the button.

(With touch simulation on desktop Firefox it works correctly)

**Comment by atstp** [comment]
This should be fixed with #29
