### ISSUE TITLE
Demo doesn't work.

### ISSUE THREAD

**Issue by bman654** [CliffCloud/Leaflet.sleep#3]
I just tried the demo: http://cliffcloud.github.io/Leaflet.Sleep/#summary

And everytime I used the mousewheel to scroll, as soon as the page scrolled so the map was under the mouse, the map would start zooming instead.

Chrome Version 44.0.2403.157 m
Windows 7 64bit.

**Comment by atstp** [comment]
Hmm, that's no good... 

just to make sure we're on the same page here's an annotated screenshot:

> ![leaflet_sleep](https://cloud.githubusercontent.com/assets/5891072/9506557/a3ee9962-4bfd-11e5-84e3-207b893ec4f8.png)

The maps up higher just serve to demonstrate the scroll-capture issue, the one at the bottom is the only one with sleep enabled.  Do you see the sleep message on that one?

the bottom (sleeping) map should wake up after 750ms and function normally.

(perhaps, this is unnecessary, but it's nice to cover all the bases before a bug hunt. on that note, thanks for the version info!)

**Comment by bman654** [comment]
Ah yes indeed it works like you describe.  User error.  Though it is unclear from the text on the page what is supposed to happen :)

**Comment by atstp** [comment]
I'll increase the sleep time to make it a little more straightforward.

Any thoughts on what would make it more clear in the description?

**Comment by bman654** [comment]
Maybe something at the top of the demo page (and the README) that says what problem the plugin is solving.

Something like:

```
Normally when you use your mousewheel to scroll through a page that contains a Leaflet map, once the page scrolls such that the map is under the cursor, the page stops scrolling and the map starts zooming.  This is annoying!

This plugin solves this problem.

Try scrolling this page and observe how the first two maps capture the mousewheel and start zooming.  But the third map does not, since it is using the plugin.
```
