### ISSUE TITLE
Overlay message masks events even when faded

### ISSUE THREAD

**Issue by si-the-pie** [CliffCloud/Leaflet.sleep#9]
When the 'Click to Wake' message disappears it leaves behind a dead area right in the centre of the map that does not transmit hover or click events through to the layers (such as markers) beneath. I think this is because the message layer has opacity set to zero rather than being completely removed.

**Comment by atstp** [comment]
good catch, it's good to go now :ok_hand: 

For supporting IE10 or lower, check [this](https://github.com/kmewhort/pointer_events_polyfill) out, and on the off-chance that doesn't cut it, let me know and we can go with a heavier-handed solution.
